CREATE SCHEMA EC4_SI1N;
USE EC4_SI1N;

CREATE TABLE IF NOT EXISTS ALUNOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE,
    ENDERECO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    ESPECIALIDADE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS MODALIDADES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE IF NOT EXISTS PLANOS_TREINAMENTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    ALUNO_ID INT,
    INSTRUTOR_ID INT,
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ID),
    FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(ID)
);

CREATE TABLE IF NOT EXISTS AULAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_HORA DATETIME NOT NULL,
    CAPACIDADE INT NOT NULL,
    MODALIDADE_ID INT,
    INSTRUTOR_ID INT,
    FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADES(ID),
    FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(ID)
);

CREATE TABLE IF NOT EXISTS INSCRICOES_AULAS (
    AULA_ID INT,
    ALUNO_ID INT,
    PRIMARY KEY (AULA_ID, ALUNO_ID),
    FOREIGN KEY (AULA_ID) REFERENCES AULAS(ID),
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ID)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA DATE NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
    ALUNO_ID INT,
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ID)
);

CREATE TABLE IF NOT EXISTS MATRICULAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_MATRICULA DATE NOT NULL,
    MODALIDADE_ID INT,
    ALUNO_ID INT,
    FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADES(ID),
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ID)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES_MODALIDADES (
    INSTRUTOR_ID INT,
    MODALIDADE_ID INT,
    PRIMARY KEY (INSTRUTOR_ID, MODALIDADE_ID),
    FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(ID),
    FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADES(ID)
);

#COMANDOS ALTER E DROP

ALTER TABLE ALUNOS ADD COLUMN EMAIL VARCHAR(100);

ALTER TABLE INSTRUTORES MODIFY ESPECIALIDADE VARCHAR(150);

ALTER TABLE INSTRUTORES ADD CONSTRAINT UNIQUE (CPF);

DROP TABLE IF EXISTS INSTRUTORES_MODALIDADES;

ALTER TABLE MODALIDADES DROP COLUMN DESCRICAO;
