CREATE SCHEMA EC2_SI1N;
USE EC2_SI1N;

CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    TELEFONE VARCHAR(15),
    ENDERECO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    CODIGO CHAR(3) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    PAIS VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS AERONAVES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(50) NOT NULL,
    CAPACIDADE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    FUNCAO ENUM('PILOTO', 'COMISSARIO', 'EQUIPE DE SOLO') NOT NULL,
    TELEFONE VARCHAR(15),
    CPF VARCHAR(11) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS (
    CODIGO CHAR(6) PRIMARY KEY,
    ORIGEM CHAR(3),
    DESTINO CHAR(3),
    AERONAVE_ID INT,
    HORARIO_PARTIDA DATETIME NOT NULL,
    HORARIO_CHEGADA DATETIME NOT NULL,
    FOREIGN KEY (ORIGEM) REFERENCES AEROPORTOS(CODIGO),
    FOREIGN KEY (DESTINO) REFERENCES AEROPORTOS(CODIGO),
    FOREIGN KEY (AERONAVE_ID) REFERENCES AERONAVES(ID)
);

CREATE TABLE IF NOT EXISTS OPERACOES_DE_VOO (
    VOO_CODIGO CHAR(6),
    FUNCIONARIO_ID INT,
    FUNCAO ENUM('PILOTO', 'COMISSARIO', 'EQUIPE DE SOLO') NOT NULL,
    PRIMARY KEY (VOO_CODIGO, FUNCIONARIO_ID),
    FOREIGN KEY (VOO_CODIGO) REFERENCES VOOS(CODIGO),
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIOS(ID)
);

CREATE TABLE IF NOT EXISTS RESERVAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PASSAGEIRO_ID INT NOT NULL,
    VOO_CODIGO CHAR(6) NOT NULL,
    DATA_RESERVA DATE NOT NULL,
    STATUS ENUM('CONFIRMADA', 'CANCELADA') NOT NULL,
    FOREIGN KEY (PASSAGEIRO_ID) REFERENCES PASSAGEIROS(ID),
    FOREIGN KEY (VOO_CODIGO) REFERENCES VOOS(CODIGO)
);

CREATE TABLE IF NOT EXISTS EQUIPES
(
FUNC_ID INT,
VOO_CODIGO INT,
PRIMARY KEY (FUNC_ID, VOO_CODIGO),
FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID),
FOREIGN KEY (VOO_CODIGO) REFERENCES VOOS(VOO_CODIGO)
);

#COMANDOS ALTER E DROP

ALTER TABLE PASSAGEIROS ADD COLUMN EMAIL VARCHAR(100);

ALTER TABLE FUNCIONARIOS DROP COLUMN TELEFONE;

ALTER TABLE AEROPORTOS MODIFY NOME VARCHAR(150);

DROP TABLE IF EXISTS OPERACOES_DE_VOO;

ALTER TABLE FUNCIONARIOS ADD CONSTRAINT UNIQUE (CPF);
